[package]
name = "voicevox_core_ruby_api"
version = "0.1.0"
edition = "2021"
authors = ["sevenc-nanashi <sevenc7c@sevenc7c.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
